# To use the file simple add a variable <program-name>_OBJS = <object files needed by program>
# and then you can simply use "make <program-name>"

step_counter_test_OBJS = step_count_test.o $(MODULES)/step_count.o

# The base of the make file
include ../common.mk